spring.application.name=semana4-api-rest
server.port=8083 
# Muestra detalles básicos de error durante el laboratorio.
# En producción no se recomienda exponer mensajes internos.
server.error.include-message=always
server.error.include-binding-errors=always

# Configuración de BD H2 en memoria
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Habilitar consola web de H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Configuración de JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

