-- =============================================================================
-- ESQUEMA INICIAL DE BASE DE DATOS (PHANTOM_DB)
-- MIGRACIÓN V1 - FLYWAY
-- =============================================================================

-- 1. TABLA: CATEGORIAS
CREATE TABLE "public"."categorias" (
  "id"          bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "nombre"      varchar(100) NOT NULL,
  "descripcion" varchar(255),
  CONSTRAINT "categorias_pkey" PRIMARY KEY ("id")
);

-- 2. TABLA: USUARIOS
CREATE TABLE "public"."usuarios" (
  "id"              bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "nombre"          varchar(255) NOT NULL,
  "email"           varchar(255) NOT NULL,
  "password"        varchar(255),
  "rol"             varchar(50) NOT NULL DEFAULT 'USER',
  "dni"             varchar(20),
  "direccion"       varchar(255),
  "numero_telefono" varchar(20),
  "fecha_registro"  timestamp without time zone DEFAULT now(),
  CONSTRAINT "usuarios_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "usuarios_email_key" UNIQUE ("email"),
  CONSTRAINT "unique_dni" UNIQUE ("dni")
);

-- 3. TABLA: PERFILES
CREATE TABLE "public"."perfiles" (
  "id"         bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "avatar_url" varchar(255),
  "biografia"  varchar(255),
  "usuario_id" bigint NOT NULL,
  CONSTRAINT "perfiles_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "perfiles_usuario_id_key" UNIQUE ("usuario_id"),
  CONSTRAINT "fk_perfiles_usuario" FOREIGN KEY ("usuario_id") REFERENCES "public"."usuarios"("id") ON DELETE CASCADE
);

-- 4. TABLA: PRODUCTOS
CREATE TABLE "public"."productos" (
  "id"           bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "nombre"       varchar(150) NOT NULL,
  "descripcion"  varchar(1000),
  "precio"       numeric(10,2) NOT NULL,
  "stock"        integer NOT NULL DEFAULT 0,
  "marca"        varchar(100),
  "imagen_url"   varchar(1000),
  "categoria_id" bigint NOT NULL,
  CONSTRAINT "productos_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "fk_productos_categoria" FOREIGN KEY ("categoria_id") REFERENCES "public"."categorias"("id") ON DELETE RESTRICT
);

-- 5. TABLA: ETIQUETAS
CREATE TABLE "public"."etiquetas" (
  "id"     bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "nombre" varchar(50) NOT NULL,
  CONSTRAINT "etiquetas_pkey" PRIMARY KEY ("id")
);

-- 6. TABLA INTERMEDIA: PRODUCTO_ETIQUETA (Muchos a Muchos)
CREATE TABLE "public"."producto_etiqueta" (
  "producto_id" bigint NOT NULL,
  "etiqueta_id" bigint NOT NULL,
  CONSTRAINT "producto_etiqueta_pkey" PRIMARY KEY ("producto_id", "etiqueta_id"),
  CONSTRAINT "fk_pe_producto" FOREIGN KEY ("producto_id") REFERENCES "public"."productos"("id") ON DELETE CASCADE,
  CONSTRAINT "fk_pe_etiqueta" FOREIGN KEY ("etiqueta_id") REFERENCES "public"."etiquetas"("id") ON DELETE CASCADE
);

-- 7. TABLA: VENTAS
CREATE TABLE "public"."ventas" (
  "id"             bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "fecha"          timestamp without time zone DEFAULT now(),
  "total"          numeric(10,2) NOT NULL,
  "cantidad_items" integer NOT NULL,
  "usuario_id"     bigint,
  "numero_orden"   text,
  CONSTRAINT "ventas_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "ventas_numero_orden_key" UNIQUE ("numero_orden"),
  CONSTRAINT "fk_ventas_usuario" FOREIGN KEY ("usuario_id") REFERENCES "public"."usuarios"("id") ON DELETE SET NULL
);

-- 8. TABLA: DETALLE_VENTAS
CREATE TABLE "public"."detalle_ventas" (
  "id"              bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "venta_id"        bigint NOT NULL,
  "producto_id"     bigint NOT NULL,
  "cantidad"        integer NOT NULL,
  "precio_unitario" numeric(10,2) NOT NULL,
  "subtotal"        numeric(10,2) NOT NULL,
  CONSTRAINT "detalle_ventas_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "fk_detalle_venta" FOREIGN KEY ("venta_id") REFERENCES "public"."ventas"("id") ON DELETE CASCADE,
  CONSTRAINT "fk_detalle_producto" FOREIGN KEY ("producto_id") REFERENCES "public"."productos"("id") ON DELETE RESTRICT
);